---
## output dir
output_prefix: "output_flip_new_honey"
time_step: 0.04
simulation_time: 8

radius:  1
init_vel_x: 0
init_vel_y: 0
init_vel_z: 0

obj-pos-x: 0
obj-pos-y: 0
obj-pos-z: 0

FLIP_domain_collision: true
FLIP_domain_solid: false
FLIP_solid_friction: 0.0
FLIPCFL: 3
FLIP_min_step_num: 1
FLIP_max_step_num: 10

pressure_acc: 1e-4
viscosity_acc: 1e-3

FLIPpool-minx: -2
FLIPpool-miny: 0
FLIPpool-minz: -2
FLIPpool-maxx: 3
FLIPpool-maxy: 8
FLIPpool-maxz: 2
FLIPdx:  0.096

enable_viscosity: true
viscosity_coef: 6500
solids_vdb: "strawberry.vdb"
#solids_vel_vdb
source_vdb: "source.vdb"
#source_vel_vdb

dynamic_obj_enabled: false
dynamic_obj_folder: ""
dynamic_obj_prefix: ""

